apiVersion: v1
kind: Secret
metadata:
  name: nlp-secrets
type: Opaque
stringData:
  SECRET_KEY: tr!%cn+(h$zg-8=c)6t%)n9b$h$-s1l18s85s^z1mv2)e*no5v
  MONGO_URI: mongodb://test-mongo-srv:27017/nlpdb
  DB_NAME: nlpdb
